# Site settings
name: Kudzai Mabika
title: Kudzai Mabika | Undergrad
description: Undergrand student working towards becoming a Software Engineer
url: http://localhost:3000/
baseurl: 'http://localhost:3000/'
email: kdmab10@gmail.com
cover: 
logo:   http://localhost:3000/logo.png
resume: http://localhost:3000/Kudzai_Mabika_CV.pdf
social:
  - title: email
    url: mailto:kdmab10@gmai.com
  - title: dev
    url: https://dev.to/kmabika
  - title: github
    url: https://github.com/kmabika
  - title: linkedin
    url: https://www.linkedin.com/in/kudzaimabika

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
